### PR TITLE
Unit testing setup with CMake's CTest. Using test slide from OpenPhi …

### PR DESCRIPTION
**Pull request by alex-virodov**
…- downloaded by CMake if missing.

### CODE REVIEW

**Comment by alex-virodov** [comment]
Note: this setup requires a big download (0.5Gb) even if you don't intend to run tests. And it was not fast for me unfortunately, and I couldn't figure out how to make CMake to download only if you test. If this is not acceptable, let's discuss alternatives.

**Comment by bgilbert** [comment]
> Note: this setup requires a big download (0.5Gb) even if you don't intend to run tests.

Linux distros, at least, build their packages on builders that have Internet access disabled.  Downstream packaging would thus need to patch this out.

**Comment by Falcury** [comment]
The tests seem to work OK for me! I made a PR #15 that disables the tests by default (and with it, the downloading of the test slide). @alex-virodov Could you check if that works for you?

**Review by Falcury — APPROVED** [review]

**Comment by alex-virodov** [comment]
Better implementation in #15 .

**Pull request closed without merging**
