### PR TITLE
NEON support for convert_ycocg_to_bgra_block

### PR DESCRIPTION
**Pull request by jonasteuwen**
As requested. By the way, this assumes the tile_size is divisible by 8. I assume this will be always fine, but we never check for this (maybe an assert?)

### CODE REVIEW

**Comment by Falcury** [comment]
Thanks! I'll test it as soon as I can.

> By the way, this assumes the tile_size is divisible by 8. I assume this will be always fine, but we never check for this (maybe an assert?)

I think I made an error in the logic, which you also [fixed](https://github.com/amspath/libisyntax/pull/7/files#diff-8bfee7c633097e2bc67c28ca9589680e572526e97472c4dce0e308f1605aef2bR3206-R3241) for `bgra_to_rgba()` in your other PR.

**Comment by jonasteuwen** [comment]
So, perhaps we should implement this. An enum with choices: "bgra" (opencv2) "argb" (openslide), "rgba" (rest of the world) and then a few specific function to convert it. I can implement them using SIMD if you wish.

**Comment by bgilbert** [comment]
Assuming that those are `uint8_t[4]` rather than `uint32_t`, OpenSlide would also want BGRA except on big-endian machines.  If desired, I think it's okay to omit ARGB and make OpenSlide do its own byte swapping on big-endian.

**Comment by Falcury** [comment]
@jonasteuwen I merged the PR, and fixed the 8-element divisibility issue by processing any unaligned elements at the end using the slow version.

> So, perhaps we should implement this. An enum with choices: "bgra" (opencv2) "argb" (openslide), "rgba" (rest of the world) and then a few specific function to convert it. I can implement them using SIMD if you wish.

I added `convert_ycocg_to_rgba_block()` here: 5e6a9e4d2d8cbfa1c2b7384e25b7830defd0df22
Hopefully I did that right.

I think it's interesting that the NEON version ended up so much shorter and more elegant than my x86 version. I wonder if the x86 version can be improved.

If you want to give adjusting the API a shot to deal with the color spaces, sure.

**Pull request merged**
